
services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: shiguang-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root           # MySQL 根用户密码（对应 settings.py 中的 'PASSWORD'）
      MYSQL_DATABASE: shiguang    # 默认数据库名（对应 settings.py 中的 'NAME'）
      MYSQL_USER: root             # 可选：自定义数据库用户（如使用非 root 用户）
      MYSQL_PASSWORD: root     # 可选：自定义用户密码
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: shiguang-redis
    ports:
      - "6379:6379"

  # Django 后端服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shiguang-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
  static_volume: