# Generated by Django 5.2.3 on 2025-06-29 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('已接受', '已接受'), ('待确认', '待确认'), ('已拒绝', '已拒绝')], max_length=10, verbose_name='好友关系状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=60, null=True, verbose_name='好友备注')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendship', to=settings.AUTH_USER_MODEL, verbose_name='本用户')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendship', to=settings.AUTH_USER_MODEL, verbose_name='好友')),
            ],
        ),
    ]
