# Generated by Django 5.2.3 on 2025-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('已接受', '已接受'), ('待确认', '待确认'), ('已拒绝', '已拒绝')], default='待确认', max_length=10, verbose_name='好友关系状态'),
        ),
    ]
