# Generated by Django 5.2.3 on 2025-06-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_alter_friendship_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': '好友关系', 'verbose_name_plural': '好友关系'},
        ),
    ]
