# Generated by Django 5.2.3 on 2025-06-26 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名用户', max_length=50, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', '公开账户'), ('friend', '好友账户'), ('privacy', '私密账户')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='register_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 2, 23, 2, 785490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
    ]
