# Generated by Django 5.2.3 on 2025-06-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_birthday_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
