# Generated by Django 5.2.3 on 2025-06-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_register_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='匿名用户', max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', '公开账户'), ('friend', '好友账户'), ('privacy', '私密账户')], default='public', max_length=10, verbose_name='账户可见性'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
